# You can enable features that affect all services here.
# global:
#   telemetry:
#     prometheus:
#       enabled: true

nameOverride: ""
fullnameOverride: ""

# subcharts
spire-server:
  enabled: true
  nameOverride: server
  bundleConfigMap: &bundleConfigMap spire-bundle

  clusterName: &clusterName "example-cluster"
  trustDomain: &trustDomain "example.org"

  controllerManager:
    enabled: true

spire-agent:
  enabled: true
  nameOverride: agent
  bundleConfigMap: *bundleConfigMap

  clusterName: *clusterName
  trustDomain: *trustDomain

upstream:
  # -- enable upstream csi driver and agent for use with nested spire.
  enabled: false

upstream-spire-agent:
  nameOverride: agent-upstream
  bundleConfigMap: spire-bundle-upstream

  clusterName: *clusterName
  trustDomain: *trustDomain

  socketPath: /run/spire/agent-sockets-upstream/spire-agent.sock
  serviceAccount:
    name: spire-agent-upstream
  healthChecks:
    port: 9981

spiffe-csi-driver:
  enabled: true

upstream-spiffe-csi-driver:
  pluginName: upstream.csi.spiffe.io
  agentSocketPath: /run/spire/agent-sockets-upstream/spire-agent.sock
  healthChecks:
    port: 9810

spiffe-oidc-discovery-provider:
  enabled: false
  trustDomain: *trustDomain
